name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build-release && cd build-release && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cmake --build build-release
    
  build-windows-2016:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build-release && cd build-release && cmake ..
    - name: build
      run: cmake --build build-release --config Release

  build-windows-latest:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build-release;cd build-release;cmake ..
    - name: build
      run: cmake --build build-release --config Release


